### ISSUE TITLE
Awesome work, but scroll wheel doesn't work in Xcode 6.x with OS X 10.10.2

### ISSUE THREAD

**Issue by ipatch** [pmj/QemuUSBTablet-OSX#1]
Really appreciate the driver :D but I am unable to get the scroll wheel to work in Xcode 6.x and OS X 10.10.2.  Once again can't say enough how awesome this project is, and could be.

**Comment by pmj** [comment]
Sorry, I was really ill when you reported this, and I've forgotten about it until now. If you're still having this problem, would you mind posting your configuration? qemu & kvm versions and qemu command line would be a good start.

**Comment by pmj** [comment]
I'm closing this due to lack of updates and as I haven't been able to repro it. If anyone is still having this problem with version 1.2 of the driver, please re-open with extra info. (Such as what Qemu video frontend you're using - e.g. VNC, SPICE, SDL, GTK, etc.)
